name: Create and publish release

env:
  IMAGE_NAME: nbe95/nc2ldap

on:
  push:
    branches:
      - main

jobs:
  tag-version:
    name: Tag new version
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: read
      pull-requests: read
    outputs:
      version: ${{ steps.semver.outputs.version }}
      sha: ${{ steps.commit.outputs.sha }}
    steps:
      - uses: actions/checkout@v7
      - name: Get commit data
        id: commit
        run: |
          echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - uses: jefflinse/pr-semver-bump@v1.7.4
        name: Bump and tag new version
        id: semver
        with:
          mode: bump
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          major-label: major
          minor-label: minor
          patch-label: patch
          noop-labels: ""
          require-release-notes: false
          base-branch: true
          with-v: false

  docker-image:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs:
      - tag-version
    steps:
      - uses: actions/checkout@v7
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Extract version tags
        id: version-tags
        run: |
          VERSION="${{ needs.tag-version.outputs.version }}"
          FULL_VERSION=$VERSION
          MAJOR_MINOR=$(echo $VERSION | cut -d. -f1-2)
          MAJOR=$(echo $VERSION | cut -d. -f1)
          echo "full_version=$FULL_VERSION" >> $GITHUB_OUTPUT
          echo "major_minor=$MAJOR_MINOR" >> $GITHUB_OUTPUT
          echo "major=$MAJOR" >> $GITHUB_OUTPUT
      - name: Build and push image
        uses: docker/build-push-action@v7
        with:
          build-args: |
            VERSION=${{ needs.tag-version.outputs.version }}
            VERSION_SHA=${{ needs.tag-version.outputs.sha }}
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.version-tags.outputs.full_version }}
            ${{ env.IMAGE_NAME }}:${{ steps.version-tags.outputs.major_minor }}
            ${{ env.IMAGE_NAME }}:${{ steps.version-tags.outputs.major }}
            ${{ env.IMAGE_NAME }}:latest
